apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: stuj7qsuk-python
  janus-idp.io/tekton: stuj7qsuk-python
  backstage.io/kubernetes-id: stuj7qsuk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: stuj7qsuk-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
