apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: stuj7qsuk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: stuj7qsuk-python 
  name: stuj7qsuk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: stuj7qsuk-python 
